- name: Create Mattermost System User
  user:
      name: mattermost 
      create_home: no 
      home: /opt/mattermost
      shell: /usr/sbin/nologin

- name: Download Mattermost
  unarchive:
      src: "{{mattermost_download_url}}"
      dest: /opt/ 
      group: mattermost 
      remote_src: yes
      owner: mattermost
      mode: g+w

- name: Create the storage directory for files.
  file:
      path: /opt/mattermost/data
      state: directory 
      owner: mattermost 
      group: mattermost
      mode: g+w
      
- name: Set up the database driver
  template:
    src: config.json.jinja2
    dest: /opt/mattermost/config/config.json

- name: Setup Mattermost to use systemd for starting and stopping.
  copy:
    src: mattermost.service
    dest: /lib/systemd/system/mattermost.service

- name: Start Mattermost
  service:
    name: mattermost
    state: started
    enabled: yes

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes